# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iev-expense' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iev-expense

  target 'iev-expenseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iev-expenseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
